name: livinkey
description: PG Management App for India
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.3.8
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.0
  audioplayers: ^5.2.1
  image_picker: ^1.0.4
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  
  # NEW: Firebase Push Notification Dependencies
  firebase_core: ^2.24.2
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^17.0.0
  app_badge_plus: ^1.1.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#0D0D0D"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#0D0D0D"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true